"""fixed shows table.

Revision ID: 26c757f395a9
Revises: ad00a4ce7a90
Create Date: 2020-10-04 11:23:04.416631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c757f395a9'
down_revision = 'ad00a4ce7a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PastShow', 'name')
    op.drop_column('UpcomingShow', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UpcomingShow', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('PastShow', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
