"""Added area table.

Revision ID: da8a86411b99
Revises: f2f003fce5b4
Create Date: 2020-10-03 19:23:16.036158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8a86411b99'
down_revision = 'f2f003fce5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'area_id')
    op.drop_table('Area')
    # ### end Alembic commands ###
